### ISSUE TITLE
BSC-Relayer v1.1.0 is not working at any platform

### ISSUE THREAD

**Issue by moesaleh** [binance-chain/bsc-relayer#30]
Hello,
I tried and built the bscrelayer in Linux, Mac, and even windows, but it's not working.
Here below my configuration:
{
  "cross_chain_config": {
    "source_chain_id": 1,
    "dest_chain_id": 2,
    "monitor_channel_list": [1, 2, 3, 8, 9],
    "competition_mode": true
  },
  "bbc_config": {
    "rpc_addrs": [
      "https://dataseed1.binance.org:80"
    ],
    "mnemonic_type": "local_mnemonic",
    "aws_region": "",
    "aws_secret_name": "",
    "mnemonic": "*********************************************************",
    "sleep_millisecond_for_wait_block": 500,
    "clean_up_block_interval": 20,
    "block_interval_for_clean_up_undelivered_packages": 1000,
    "behind_block_threshold": 100
  },
  "bsc_config": {
    "key_type": "local_private_key",
    "aws_region": "",
    "aws_secret_name": "",
    "private_key": "******************************************************",
    "providers": [
      "https://bsc-dataseed1.binance.org"
    ],
    "gas_limit": 4700000,
    "gas_price": 20000000000,
	"unconfirmed_tx_threshold": 1,
    "monitor_data_seed_list": [
	  "wss://bsc-dataseed1.binance.org:443",
        "wss://bsc-dataseed2.binance.org:443",
        "wss://bsc-dataseed3.binance.org:443",
        "wss://bsc-dataseed4.binance.org:443",
        "wss://bsc-dataseed1.defibit.io:443",
        "wss://bsc-dataseed2.defibit.io:443",
        "wss://bsc-dataseed3.defibit.io:443",
        "wss://bsc-dataseed4.defibit.io:443",
        "wss://bsc-dataseed1.ninicoin.io:443",
        "wss://bsc-dataseed2.ninicoin.io:443",
        "wss://bsc-dataseed3.ninicoin.io:443",
        "wss://bsc-dataseed4.ninicoin.io:443"

	]
  },
  "log_config": {
    "level": "DEBUG",
    "filename": "",
    "max_file_size_in_mb": 0,
    "max_backups_of_log_files": 0,
    "max_age_to_retain_log_files_in_days": 0,
    "use_console_logger": true,
    "use_file_logger": false,
    "compress": false
  },
  "db_config": {
    "dialect": "mysql",
    "db_path": ""
  },
  "admin_config": {
    "listen_addr": "127.0.0.1:9090"
  },
  "alert_config": {
    "enable_alert": false,
    "enable_heart_beat": false,
    "interval": 300,
    "identity": "your_service_name",
    "telegram_bot_id": "your_bot_id",
    "telegram_chat_id": "your_chat_id",
    "balance_threshold": "1000000000000000000",
    "sequence_gap_threshold": 10
  }
}

It keeps showing this error:
2021-06-27 02:00:30 INFO Serve start admin server at 127.0.0.1:9090
2021-06-27 02:00:32 INFO main Starting relayer
2021-06-27 02:00:33 INFO registerRelayerHub This relayer has already been registered
2021-06-27 02:00:33 INFO cleanPreviousPackages Cleanup packages at height 172252031
2021-06-27 02:00:34 INFO cleanPreviousPackages channelID: 1, next deliver sequence 77 on BSC, next sequence 0 on BC
2021-06-27 02:00:35 INFO cleanPreviousPackages channelID: 2, next deliver sequence 8947049 on BSC, next sequence 0 on BC
2021-06-27 02:00:35 INFO cleanPreviousPackages channelID: 3, next deliver sequence 7226 on BSC, next sequence 0 on BC
2021-06-27 02:00:36 INFO cleanPreviousPackages channelID: 8, next deliver sequence 317 on BSC, next sequence 0 on BC
2021-06-27 02:00:36 INFO cleanPreviousPackages channelID: 9, next deliver sequence 6 on BSC, next sequence 0 on BC
2021-06-27 02:00:36 INFO relayerCompetitionDaemon Start relayer daemon in competition mode
2021-06-27 02:00:36 INFO UpdateClients Start to monitor bc data-seeds healthy
2021-06-27 02:00:36 INFO UpdateClients Start to monitor bsc data-seeds healthy
panic: websocket: bad handshake (HTTP status 200 OK)

goroutine 110 [running]:
github.com/binance-chain/bsc-relayer/relayer.(*Relayer).doubleSignMonitorDaemon(0xc00000e620)
	/home/mas/bscrelayer/bsc-relayer-master/relayer/double_sign_monitor.go:138 +0x6c4
created by github.com/binance-chain/bsc-relayer/relayer.(*Relayer).Start
	/home/mas/bscrelayer/bsc-relayer-master/relayer/relayer.go:49 +0x1a2

The error websocket: bad handshake (HTTP status 200 OK) is a bug occurs when the ethclient tries to establish a socket connection with the BSC data seeds, the package should be updated and use the latest version of eth-go, they fixed this bug.

I wonder did you guys test this release? is it working with anyone?

**Comment by moesaleh** [comment]
Hello @HaoyangLiu @guagualvcha, unfortunately, there is no official support for the BSC Relayer, so I wonder guys can you help out here?
I am attaching the output detailed errors
[BSCRelayerOutputErrorsAndLogs.log](https://github.com/binance-chain/bsc-relayer/files/6721386/BSCRelayerOutputErrorsAndLogs.log)

and the configuration file:
[BSCConfigFile.txt](https://github.com/binance-chain/bsc-relayer/files/6721389/BSCConfigFile.txt)

It's been more than 48 hours of tries, I tried too many different things, and right now I feel that am lost, I really appreciate your support.

To conclude the errors, the following errors keeps repeating till we reach the doublesign error where it cannot process the bsc providers list:
2021-06-27 12:54:33 ERROR getLatestHeight Query latest height error: websocket client is dialing or stopped, can't send any request
2021-06-27 12:54:33 INFO cleanPreviousPackages Cleanup packages at height 18446744073709551615
2021-06-27 12:54:33 INFO SwitchBCClient Switch to RPC endpoint: https://dataseed1.ninicoin.io:80
2021-06-27 12:54:33 ERROR relayerCompetitionDaemon websocket client is dialing or stopped, can't send any request
2021-06-27 12:54:33 ERROR getLatestHeight Query latest height error: websocket client is dialing or stopped, can't send any request
2021-06-27 12:54:33 INFO cleanPreviousPackages Cleanup packages at height 18446744073709551615
2021-06-27 12:54:33 INFO SwitchBCClient Switch to RPC endpoint: https://dataseed1.ninicoin.io:80
2021-06-27 12:54:33 ERROR relayerCompetitionDaemon websocket client is dialing or stopped, can't send any request
2021-06-27 12:54:33 ERROR getLatestHeight Query latest height error: websocket client is dialing or stopped, can't send any request
2021-06-27 12:54:33 INFO cleanPreviousPackages Cleanup packages at height 18446744073709551615
2021-06-27 12:54:33 INFO SwitchBCClient Switch to RPC endpoint: https://dataseed1.ninicoin.io:80
2021-06-27 12:54:33 ERROR relayerCompetitionDaemon websocket client is dialing or stopped, can't send any request
2021-06-27 12:54:33 ERROR getLatestHeight Query latest height error: websocket client is dialing or stopped, can't send any request
2021-06-27 12:54:33 INFO cleanPreviousPackages Cleanup packages at height 18446744073709551615
2021-06-27 12:54:33 INFO SwitchBCClient Switch to RPC endpoint: https://dataseed1.ninicoin.io:80
2021-06-27 12:54:33 ERROR relayerCompetitionDaemon websocket client is dialing or stopped, can't send any request

The config.json, configured as the following:
{
  "cross_chain_config": {
    "source_chain_id": 1,
    "dest_chain_id": 2,
    "monitor_channel_list": [1, 2, 3, 8, 9],
    "competition_mode": true
  },
  "bbc_config": {
    "rpc_addrs": [

"https://dataseed1.ninicoin.io:80"
	  
    ],
    "mnemonic_type": "local_mnemonic",
    "aws_region": "",
    "aws_secret_name": "",
    "mnemonic": "***********************************",
    "sleep_millisecond_for_wait_block": 500,
    "clean_up_block_interval": 20,
    "block_interval_for_clean_up_undelivered_packages": 1000,
    "behind_block_threshold": 100
  },
  "bsc_config": {
    "key_type": "local_private_key",
    "aws_region": "",
    "aws_secret_name": "",
    "private_key": "*****************************************",
    "providers": [
		"https://bsc-dataseed1.ninicoin.io"
    ],
    "gas_limit": 4700000,
    "gas_price": 20000000000,
	"unconfirmed_tx_threshold": 1,
    "monitor_data_seed_list": [
	  "wss://bsc-dataseed1.binance.org",
        "wss://bsc-dataseed2.binance.org",
        "wss://bsc-dataseed3.binance.org"
      

	]
  },
  "log_config": {
    "level": "DEBUG",
    "filename": "",
    "max_file_size_in_mb": 0,
    "max_backups_of_log_files": 0,
    "max_age_to_retain_log_files_in_days": 0,
    "use_console_logger": true,
    "use_file_logger": false,
    "compress": false
  },
  "db_config": {
    "dialect": "mysql",
    "db_path": ""
  },
  "admin_config": {
    "listen_addr": "127.0.0.1:9191"
  },
  "alert_config": {
    "enable_alert": false,
    "enable_heart_beat": false,
    "interval": 300,
    "identity": "your_service_name",
    "telegram_bot_id": "your_bot_id",
    "telegram_chat_id": "your_chat_id",
    "balance_threshold": "1000000000000000000",
    "sequence_gap_threshold": 10
  }
}

I really appreciate your answer guys.

**Comment by yutianwu** [comment]
use tcp://dataseed1.ninicoin.io:80 instead
